node('builtin') 
{
    stage('Continuous Download_master') 
	{
   git 'https://github.com/Npooj/jenkins_multiplebranch.git'
	}
    stage('Continuous Build_master') 
	{
    sh label: '', script: 'mvn package'
	}
    
}
