node('builtin') 
{
    stage('Continuous Download_loans') 
	{
    git 'https://github.com/Npooj/jenkins_multiplebranch.git'
	}
    stage('Continuous Build_loans') 
	{
    sh label: '', script: 'mvn package'
	}
    
}
